modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "${issues}" #optional

[[mods]] #mandatory
modId = "${forge_mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "${sources}" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional
credits = "${credits}" #optional
authors = "${mod_author}" #optional
description = '''${mod_description}''' #mandatory (Supports multiline text)

[[dependencies.${forge_mod_id}]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_loader_version_range}" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "CLIENT" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${forge_mod_id}]]
modId = "minecraft"
mandatory = true #mandatory
versionRange = "${minecraft_version_range_maven}"
ordering = "NONE"
side = "CLIENT"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
