name: Add Contributor
description: Add Contributor to fabric.mod.json
inputs:
  contributor:
    description: 'Contributor name'
    required: true
  fmj-path:
    description: 'Path to fabric.mod.json'
    default: src/main/resources/fabric.mod.json
    required: false
  token:
    description: 'Github token'
    default: ${{ github.token }}
    required: false
  branch:
    description: 'Target branch'
    default: ${{ github.ref }}
    required: false
  message:
    description: 'Commit message'
    required: false
    default: Add Contributor
runs:
  using: composite
  steps:
    - name: Update Contributors
      shell: bash
      run: |
        echo "`jq --arg name "${{ inputs.contributor }}" '.contributors[.contributors | length] = $name' \
          ${{ inputs.fmj-path }}`" > ${{ inputs.fmj-path }}
        echo "Added ${{ inputs.contributor }} to the list of contributors"
    - name: Commit files
      shell: bash
      run: |
        echo "Committing fabric.mod.json..."
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "${{ inputs.message }}"
        echo "Pushing changes..."
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}