modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.

[[mods]] #mandatory
modId = "testmod" #mandatory
version = "0.0.1" #mandatory
displayName = "Minecraft Cursor-TestMod" #mandatory
description = "" #mandatory (Supports multiline text)

[[mixins]]
config = "testmod.mixins.json"

[[dependencies.testmod]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${neoforge_version_range}" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "CLIENT" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.testmod]]
modId = "minecraft"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${minecraft_version_range_maven}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.testmod]]
modId = "minecraft_cursor"
type = "required"
versionRange = "${version}"
ordering = "NONE"
side = "CLIENT"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
