plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id 'java-library'
}

tasks.build.dependsOn tasks.jarJar

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url = "https://maven.ftb.dev/releases"
            }
        }
        filter {
            includeGroup "dev.ftb.mods"
        }
    }
    maven {
        url "https://maven.architectury.dev/"
    }
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":commonApi").sourceSets.main
        }
        testmod {
            sourceSet sourceSets.testmod
        }
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
            setIdeName("Forge Client (${project.path})")
            loadedMods = [mods."${mod_id}"]
        }
        testmodClient {
            client()
            gameDirectory = project.file('run/testmod')
            setIdeName("Forge Client Test (${project.path})")
            sourceSet = sourceSets.testmod
            programArgument("--mixin.config=testmod.mixins.json")
        }
    }
}

dependencies {
    api project(":commonApi")
    jarJar(project(":commonApi"))

    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'

    implementation 'org.jetbrains:annotations:26.0.2'

    modCompileOnly "dev.ftb.mods:ftb-library-forge:$ftb_library_version"
    modRuntimeOnly "dev.ftb.mods:ftb-library-forge:$ftb_library_version"
    modRuntimeOnly "dev.ftb.mods:ftb-quests-forge:$ftb_quests_version"
    modRuntimeOnly "dev.ftb.mods:ftb-teams-forge:$ftb_teams_version"
    modRuntimeOnly "dev.architectury:architectury-forge:$architectury_version"
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

jar {
    finalizedBy("reobfJar")
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}
