import groovy.json.JsonOutput
import groovy.json.JsonSlurper

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url = "https://maven.ftb.dev/releases"
            }
        }
        filter {
            includeGroup "dev.ftb.mods"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://maven.architectury.dev/"
    }
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":commonApi").sourceSets.main
        }
        testmod {
            sourceSet sourceSets.testmod
        }
    }
    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
            setIdeName("NeoForge Client (${project.path})")
            loadedMods = [mods."${mod_id}"]
        }
        testmodClient {
            client()
            gameDirectory = project.file('run/testmod')
            setIdeName("NeoForge Client Test (${project.path})")
            sourceSet = sourceSets.testmod
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    jarJar(api project(":commonApi"))

    compileOnly "dev.ftb.mods:ftb-library-neoforge:$ftb_library_version"
    localRuntime "dev.ftb.mods:ftb-library-neoforge:$ftb_library_version"
    localRuntime "dev.ftb.mods:ftb-quests-neoforge:$ftb_quests_version"
    localRuntime "dev.ftb.mods:ftb-teams-neoforge:$ftb_teams_version"
    localRuntime "dev.architectury:architectury-neoforge:$architectury_version"

    compileOnly "maven.modrinth:owo-lib:$owo_version"
}

processResources {
    doLast {
        def mixinConfigFile = file("${sourceSets.main.output.resourcesDir}/${mod_id}.mixins.json")
        if (mixinConfigFile.exists()) {
            def jsonSlurper = new JsonSlurper()
            def mixinConfig = jsonSlurper.parse(mixinConfigFile)

            mixinConfig.remove("refmap")

            mixinConfigFile.text = JsonOutput.prettyPrint(JsonOutput.toJson(mixinConfig))
        }
    }
}
