name: Cherry-Pick Translations

on:
  pull_request_target:
    types:
      - 'closed'
      - 'labeled'
    branches: [ 'master' ]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  cherry-pick:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'translation') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "1.20.1", "1.21", "1.21.2" ]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.branch }}
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Cherry pick Translation to ${{ matrix.branch }}
        id: cherry-pick
        continue-on-error: true
        run: |
          if git cherry-pick -x ${{ github.event.pull_request.merge_commit_sha }}; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            git cherry-pick --abort
            echo "status=failed" >> $GITHUB_OUTPUT
          fi
      - name: Push Changes
        if: steps.cherry-pick.outputs.status == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ matrix.branch }}
      - name: Create an Issue
        if: ${{ steps.cherry-pick.outputs.status == 'failed' || failure() }}
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Could not cherry-pick translation from PR \#${{ github.event.pull_request.number }} to ${{ matrix.branch }}
          labels: translation