

name: Publish on GitHub, CurseForge & Modrinth

on: workflow_dispatch

env:
  CURSEFORGE_ID: 1184736
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  MODRINTH_ID: o5fhgLeQ
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Set Environment Variables
        run: |
          echo "MINECRAFT_VERSION=$(./gradlew -q getProperties | grep 'MINECRAFT_VERSION' | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "VERSION=$(./gradlew -q getProperties | grep 'MOD_VERSION' | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "JAVA_VERSION=$(./gradlew -q getProperties | grep 'JAVA_VERSION' | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(./gradlew -q getProperties | grep 'RELEASE_NAME' | cut -d '=' -f2)" >> $GITHUB_ENV


      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: "${{env.CURSEFORGE_ID}}"
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: "${{env.MODRINTH_ID}}"
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
